import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784024832415 implements MigrationInterface {
    name = 'InitialSchema1784024832415'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "characterId" uuid NOT NULL, "strength" integer NOT NULL DEFAULT '10', "endurance" integer NOT NULL DEFAULT '10', "agility" integer NOT NULL DEFAULT '10', "speed" integer NOT NULL DEFAULT '10', "recovery" integer NOT NULL DEFAULT '10', "discipline" integer NOT NULL DEFAULT '10', "focus" integer NOT NULL DEFAULT '10', "programming" integer NOT NULL DEFAULT '10', "knowledge" integer NOT NULL DEFAULT '10', "charisma" integer NOT NULL DEFAULT '10', "finance" integer NOT NULL DEFAULT '10', "unallocatedPoints" integer NOT NULL DEFAULT '0', CONSTRAINT "REL_9bb9fe3b1812f0b7b6abb4f15e" UNIQUE ("characterId"), CONSTRAINT "PK_32216e2e61830211d3a5d7fa72c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."skills_type_enum" AS ENUM('active', 'passive', 'ultimate')`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "characterId" uuid NOT NULL, "name" character varying NOT NULL, "type" "public"."skills_type_enum" NOT NULL DEFAULT 'active', "level" integer NOT NULL DEFAULT '1', "unlocked" boolean NOT NULL DEFAULT false, "cooldown" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_04158568804dfd7f38431962da" ON "skills" ("characterId") `);
        await queryRunner.query(`CREATE TYPE "public"."characters_class_enum" AS ENUM('warrior', 'ranger', 'mage', 'monk', 'assassin', 'berserker', 'cleric', 'paladin', 'rogue', 'wizard', 'samurai', 'lucky')`);
        await queryRunner.query(`CREATE TABLE "characters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "class" "public"."characters_class_enum" NOT NULL DEFAULT 'warrior', "level" integer NOT NULL DEFAULT '1', "exp" integer NOT NULL DEFAULT '0', "expToNextLevel" integer NOT NULL DEFAULT '1000', "hp" integer NOT NULL DEFAULT '100', "maxHp" integer NOT NULL DEFAULT '100', "mp" integer NOT NULL DEFAULT '50', "maxMp" integer NOT NULL DEFAULT '50', "gold" integer NOT NULL DEFAULT '0', "disciplineScore" integer NOT NULL DEFAULT '0', "currentStreak" integer NOT NULL DEFAULT '0', "longestStreak" integer NOT NULL DEFAULT '0', "lastStreakDate" date, "dailyMissionCombo" integer NOT NULL DEFAULT '0', "bestDailyMissionCombo" integer NOT NULL DEFAULT '0', "lastMissionComboDate" date, "timezone" character varying NOT NULL DEFAULT 'Asia/Tashkent', "nextMainQuestAt" TIMESTAMP, "nextSideQuestAt" TIMESTAMP, "weightKg" double precision, "ageYears" integer, "totalQuestsCompleted" integer NOT NULL DEFAULT '0', "totalBossesDefeated" integer NOT NULL DEFAULT '0', "mentalEnergy" integer NOT NULL DEFAULT '100', "physicalEnergy" integer NOT NULL DEFAULT '100', "lastEnergyDecayDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_7c1bf02092d401b55ecc243ef1" UNIQUE ("userId"), CONSTRAINT "PK_9d731e05758f26b9315dac5e378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."quests_type_enum" AS ENUM('main_daily', 'side', 'recovery', 'challenge', 'punishment', 'weekly', 'monthly', 'story', 'hidden', 'legendary', 'boss_preparation', 'promotion_exam', 'seasonal', 'chain')`);
        await queryRunner.query(`CREATE TYPE "public"."quests_difficulty_enum" AS ENUM('easy', 'normal', 'hard', 'elite', 'legendary', 'mythic')`);
        await queryRunner.query(`CREATE TYPE "public"."quests_rarity_enum" AS ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic')`);
        await queryRunner.query(`CREATE TABLE "quests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "description" text, "lore" text, "type" "public"."quests_type_enum" NOT NULL DEFAULT 'main_daily', "difficulty" "public"."quests_difficulty_enum" NOT NULL DEFAULT 'normal', "rarity" "public"."quests_rarity_enum" NOT NULL DEFAULT 'common', "icon" character varying, "goal" character varying NOT NULL, "goalValue" integer NOT NULL DEFAULT '1', "xpReward" integer NOT NULL DEFAULT '0', "goldReward" integer NOT NULL DEFAULT '0', "attributeReward" jsonb, "itemRewards" jsonb, "requiredPreviousQuestId" uuid, "isChain" boolean NOT NULL DEFAULT false, "estimatedTime" integer, "expiresAt" TIMESTAMP, "active" boolean NOT NULL DEFAULT true, "cooldown" integer, "repeatable" boolean NOT NULL DEFAULT false, "dailyLimit" integer, "requiresProof" boolean NOT NULL DEFAULT false, "hidden" boolean NOT NULL DEFAULT false, "revealCondition" jsonb, "treeId" character varying, "treeOrder" integer, "failurePenalty" jsonb, CONSTRAINT "PK_a037497017b64f530fe09c75364" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."quest_progress_status_enum" AS ENUM('accepted', 'in_progress', 'complete', 'claimed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "quest_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "questId" uuid NOT NULL, "status" "public"."quest_progress_status_enum" NOT NULL DEFAULT 'accepted', "progress" integer NOT NULL DEFAULT '0', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastClaimedAt" TIMESTAMP, "claimsToday" integer NOT NULL DEFAULT '0', "lastClaimDate" date, "proofSubmittedAt" TIMESTAMP, CONSTRAINT "PK_00270f6acd4a18f1c6ae6aa216a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8621177b26aefd73dbd0900808" ON "quest_progress" ("questId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aecf84d1704010861724dddc25" ON "quest_progress" ("userId", "questId") `);
        await queryRunner.query(`CREATE TYPE "public"."workouts_type_enum" AS ENUM('strength', 'cardio', 'flexibility', 'hiit')`);
        await queryRunner.query(`CREATE TYPE "public"."workouts_difficulty_enum" AS ENUM('beginner', 'intermediate', 'advanced', 'elite')`);
        await queryRunner.query(`CREATE TABLE "workouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."workouts_type_enum" NOT NULL DEFAULT 'strength', "description" text, "difficulty" "public"."workouts_difficulty_enum" NOT NULL DEFAULT 'beginner', "muscles" jsonb, "xpValue" integer NOT NULL DEFAULT '10', "progressions" jsonb, "safetyTips" text, "reps" integer, "weight" double precision, "duration" integer, CONSTRAINT "PK_5b2319bf64a674d40237dbb1697" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workout_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "workoutId" uuid NOT NULL, "startTime" TIMESTAMP WITH TIME ZONE NOT NULL, "endTime" TIMESTAMP WITH TIME ZONE, "stats" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eea00e05dc78d40b55a588c9f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4b5ff8f7c2cb3c3c18e07cc5c" ON "workout_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82cab13dc713bfb0cff9bb76c5" ON "workout_sessions" ("workoutId") `);
        await queryRunner.query(`CREATE TYPE "public"."items_type_enum" AS ENUM('reward', 'cosmetic', 'weapon')`);
        await queryRunner.query(`CREATE TYPE "public"."items_rarity_enum" AS ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic', 'celestial')`);
        await queryRunner.query(`CREATE TYPE "public"."items_category_enum" AS ENUM('entertainment', 'food', 'recovery', 'lifestyle', 'premium')`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."items_type_enum" NOT NULL DEFAULT 'reward', "rarity" "public"."items_rarity_enum" NOT NULL DEFAULT 'common', "category" "public"."items_category_enum" NOT NULL DEFAULT 'lifestyle', "description" text, "icon" character varying, "goldPrice" integer NOT NULL DEFAULT '0', "sellValue" integer NOT NULL DEFAULT '0', "maxPerWeek" integer NOT NULL DEFAULT '0', "attackBonus" integer NOT NULL DEFAULT '0', "maxDurability" integer NOT NULL DEFAULT '0', "unlockRequirements" jsonb, "weekRotation" boolean NOT NULL DEFAULT true, "inExchange" boolean NOT NULL DEFAULT false, "exchangeExpiresAt" TIMESTAMP, "isLimited" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "itemId" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "equipped" boolean NOT NULL DEFAULT false, "remainingDurability" integer, "weeklyPurchases" integer NOT NULL DEFAULT '0', "weeklyPurchasesResetAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_505a1d2410060c8358e1b37c13" ON "inventory_items" ("itemId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_420baf8098fbc79522140645b8" ON "inventory_items" ("userId", "itemId") `);
        await queryRunner.query(`CREATE TYPE "public"."achievements_rarity_enum" AS ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic')`);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "title" character varying NOT NULL, "description" text, "howToUnlock" text, "rarity" "public"."achievements_rarity_enum" NOT NULL DEFAULT 'common', "rewards" jsonb, "points" integer NOT NULL DEFAULT '0', "icon" character varying, "hidden" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_4fe946ae1fdbc64abf0c48ecb8a" UNIQUE ("key"), CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "achievementId" uuid NOT NULL, "unlocked" boolean NOT NULL DEFAULT false, "progress" integer NOT NULL DEFAULT '0', "unlockedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3d94aba7e9ed55365f68b5e77fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a5a5816f54d0044ba5f3dc2b7" ON "user_achievements" ("achievementId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c1acd69cf91b1e353634c152dd" ON "user_achievements" ("userId", "achievementId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('quest', 'achievement', 'level_up', 'trial', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "data" jsonb, "readAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "sessionToken" character varying, "sessionExpiresAt" TIMESTAMP WITH TIME ZONE, "displayName" character varying, "avatarUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_84a107ea3fe90e8d9d24f10be1" ON "users" ("sessionToken") `);
        await queryRunner.query(`CREATE TABLE "world_bosses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "lore" text NOT NULL, "tier" character varying NOT NULL DEFAULT 'common', "requirements" jsonb, "rewards" jsonb, "hp" bigint NOT NULL, "maxHp" bigint NOT NULL, "weekNumber" integer NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c6d301ef09f2ae7d1cb2a7de667" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "boss_damage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bossId" uuid NOT NULL, "damageDealt" integer NOT NULL, "exerciseType" character varying NOT NULL, "amount" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_224ebaf7376c93ae3f2e5e79523" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bfd1616299e9e6ed019b0eb3e" ON "boss_damage" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be617d28cd70495998731313b2" ON "boss_damage" ("bossId") `);
        await queryRunner.query(`CREATE TYPE "public"."chronicles_type_enum" AS ENUM('quest', 'boss', 'promotion', 'story', 'event', 'reward')`);
        await queryRunner.query(`CREATE TABLE "chronicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "type" "public"."chronicles_type_enum" NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_298a88d5960505b1e56dc911da9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f7433ba1173beca901bdf2fec" ON "chronicles" ("userId") `);
        await queryRunner.query(`ALTER TABLE "attributes" ADD CONSTRAINT "FK_9bb9fe3b1812f0b7b6abb4f15ef" FOREIGN KEY ("characterId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_04158568804dfd7f38431962dab" FOREIGN KEY ("characterId") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_7c1bf02092d401b55ecc243ef1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quest_progress" ADD CONSTRAINT "FK_e6bcb2d5aac8c60d38f67f32dec" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quest_progress" ADD CONSTRAINT "FK_8621177b26aefd73dbd09008080" FOREIGN KEY ("questId") REFERENCES "quests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_b4b5ff8f7c2cb3c3c18e07cc5ce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" ADD CONSTRAINT "FK_82cab13dc713bfb0cff9bb76c54" FOREIGN KEY ("workoutId") REFERENCES "workouts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_e11f318801d41b478302f20760d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_505a1d2410060c8358e1b37c131" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74" FOREIGN KEY ("achievementId") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boss_damage" ADD CONSTRAINT "FK_3bfd1616299e9e6ed019b0eb3e9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boss_damage" ADD CONSTRAINT "FK_be617d28cd70495998731313b22" FOREIGN KEY ("bossId") REFERENCES "world_bosses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "boss_damage" DROP CONSTRAINT "FK_be617d28cd70495998731313b22"`);
        await queryRunner.query(`ALTER TABLE "boss_damage" DROP CONSTRAINT "FK_3bfd1616299e9e6ed019b0eb3e9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_505a1d2410060c8358e1b37c131"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_e11f318801d41b478302f20760d"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_82cab13dc713bfb0cff9bb76c54"`);
        await queryRunner.query(`ALTER TABLE "workout_sessions" DROP CONSTRAINT "FK_b4b5ff8f7c2cb3c3c18e07cc5ce"`);
        await queryRunner.query(`ALTER TABLE "quest_progress" DROP CONSTRAINT "FK_8621177b26aefd73dbd09008080"`);
        await queryRunner.query(`ALTER TABLE "quest_progress" DROP CONSTRAINT "FK_e6bcb2d5aac8c60d38f67f32dec"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_7c1bf02092d401b55ecc243ef1f"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_04158568804dfd7f38431962dab"`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP CONSTRAINT "FK_9bb9fe3b1812f0b7b6abb4f15ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f7433ba1173beca901bdf2fec"`);
        await queryRunner.query(`DROP TABLE "chronicles"`);
        await queryRunner.query(`DROP TYPE "public"."chronicles_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be617d28cd70495998731313b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bfd1616299e9e6ed019b0eb3e"`);
        await queryRunner.query(`DROP TABLE "boss_damage"`);
        await queryRunner.query(`DROP TABLE "world_bosses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84a107ea3fe90e8d9d24f10be1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1acd69cf91b1e353634c152dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a5a5816f54d0044ba5f3dc2b7"`);
        await queryRunner.query(`DROP TABLE "user_achievements"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP TYPE "public"."achievements_rarity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420baf8098fbc79522140645b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_505a1d2410060c8358e1b37c13"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TYPE "public"."items_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."items_rarity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."items_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82cab13dc713bfb0cff9bb76c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4b5ff8f7c2cb3c3c18e07cc5c"`);
        await queryRunner.query(`DROP TABLE "workout_sessions"`);
        await queryRunner.query(`DROP TABLE "workouts"`);
        await queryRunner.query(`DROP TYPE "public"."workouts_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workouts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aecf84d1704010861724dddc25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8621177b26aefd73dbd0900808"`);
        await queryRunner.query(`DROP TABLE "quest_progress"`);
        await queryRunner.query(`DROP TYPE "public"."quest_progress_status_enum"`);
        await queryRunner.query(`DROP TABLE "quests"`);
        await queryRunner.query(`DROP TYPE "public"."quests_rarity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quests_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quests_type_enum"`);
        await queryRunner.query(`DROP TABLE "characters"`);
        await queryRunner.query(`DROP TYPE "public"."characters_class_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04158568804dfd7f38431962da"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TYPE "public"."skills_type_enum"`);
        await queryRunner.query(`DROP TABLE "attributes"`);
    }

}
